# Generated by Django 4.2.2 on 2024-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_token_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='телеграм'),
        ),
    ]
