# Generated by Django 5.0.2 on 2024-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150, verbose_name='продукт')),
                ('version', models.IntegerField(verbose_name='версия')),
                ('version_name', models.CharField(max_length=150, verbose_name='название версии')),
                ('is_current_version', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'версия',
            },
        ),
    ]
